version: '3.8'

services:
  fe-react:
    image: rafli27/frontend-react:latest
    container_name: fe-react-app
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080/api
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
