name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/rafli/docker-compose/nodejs-ci
            git pull origin main
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
            docker-compose -f docker-compose.yaml pull
            docker-compose -f docker-compose.yaml up -d
